---
- name: Install Nginx and cronjob 
  hosts: all
  become: true # when we install nginx we need to use sudo so it will give permission to run as root
  
  vars:
   package_name: # This is a variable that can be used to define the package name if needed in the future
    Ubuntu: apache2
    Amazon: httpd

  tasks:

    - name: Printing the OS name
      debug:
        msg: "This is Yours OS is {{ ansible_distribution }}"

    - name: Install apache webservers
      dnf:
       name: "{{ package_name['Amazon'] }}"
       state: present
      when: ansible_distribution == "Amazon" # using when condition to check the OS type it one type of conditional statement in ansible like if condition in python

    - name: Install apache webservers Ubuntu
      apt:
       name: "{{ package_name['Ubuntu'] }}"
       state: present
      when: ansible_distribution == "Ubuntu"


    # Install Nginx 
    - name: Install Nginx
      dnf: 
        name: nginx
        state: present
      when: ansible_distribution == "Amazon"

      # Install cronie
    - name: Install Cron job
      dnf: 
        name: cronie
        state: present
      when: ansible_distribution == "Amazon"
      

    - name: Ensure Nginx is started
      service:
        name: nginx
        state: started
        enabled: true
      when: ansible_distribution == "Amazon"
      
# Install Nginx 
    - name: Install Nginx
      apt: 
        name: nginx
        state: present
      when: ansible_distribution == "Ubuntu"

      # Install cronie
    - name: Install Cron job
      apt: 
        name: cronie
        state: present
      when: ansible_distribution == "Ubuntu"


      

